version: "3.8"
services:
  fastapi:
    build: fastapi
    container_name: fastapi
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
    networks:
      - backend
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    volumes:
      - ~/.fastapi/data/mongo/db:/data/db
      - ~/.fastapi/data/mongo/conf:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '1024m'
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: always
    command: ["mongod", "--oplogSize=1024", "--wiredTigerCacheSizeGB=1", "--auth", "--noscripting"]

networks:
  backend:
    driver: 'bridge'